In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
trans_df = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/trans.csv", sep=";", low_memory=False)
loan_df  = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/loan.csv",  sep=";")

In [3]:
order_df = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/order.csv",  sep=";")
card_df  = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/card.csv",   sep=";")
client_df = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/client.csv", sep=";")

In [4]:
trans_df

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,981231,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN
1056316,3627616,2935,981231,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN
1056317,3625403,2869,981231,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN
1056318,3626683,2907,981231,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN
1056319,3626540,2902,981231,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN

In [5]:
disp_df = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/disp.csv", sep=";")

In [6]:
loan_df

     loan_id  account_id    date  amount  duration  payments status
0       5314        1787  930705   96396        12    8033.0      B
1       5316        1801  930711  165960        36    4610.0      A
2       6863        9188  930728  127080        60    2118.0      A
3       5325        1843  930803  105804        36    2939.0      A
4       7240       11013  930906  274740        60    4579.0      A
..       ...         ...     ...     ...       ...       ...    ...
677     4989         105  981205  352704        48    7348.0      C
678     5221        1284  981205   52512        12    4376.0      C
679     6402        6922  981206  139488        24    5812.0      C
680     5346        1928  981206   55632        24    2318.0      C
681     6748        8645  981208  240900        60    4015.0      C

[682 rows x 7 columns]

In [7]:
order_df

      order_id  account_id bank_to  account_to  amount  k_symbol
0        29401           1      YZ    87144583  2452.0      SIPO
1        29402           2      ST    89597016  3372.7      UVER
2        29403           2      QR    13943797  7266.0      SIPO
3        29404           3      WX    83084338  1135.0      SIPO
4        29405           3      CD    24485939   327.0
...        ...         ...     ...         ...     ...       ...
6466     46334       11362      YZ    70641225  4780.0      SIPO
6467     46335       11362      MN    78507822    56.0
6468     46336       11362      ST    40799850   330.0  POJISTNE
6469     46337       11362      KL    20009470   129.0
6470     46338       11362      MN    61540514  5392.0      UVER

[6471 rows x 6 columns]

In [8]:
card_df

     card_id  disp_id     type           issued
0       1005     9285  classic  931107 00:00:00
1        104      588  classic  940119 00:00:00
2        747     4915  classic  940205 00:00:00
3         70      439  classic  940208 00:00:00
4        577     3687  classic  940215 00:00:00
..       ...      ...      ...              ...
887      125      694     gold  981226 00:00:00
888      674     4360  classic  981228 00:00:00
889      322     2063  classic  981228 00:00:00
890      685     4467  classic  981229 00:00:00
891      635     4083  classic  981229 00:00:00

[892 rows x 4 columns]

In [9]:
client_df

      client_id  birth_number  district_id
0             1        706213           18
1             2        450204            1
2             3        406009            1
3             4        561201            5
4             5        605703            5
...         ...           ...          ...
5364      13955        456030            1
5365      13956        430406            1
5366      13968        680413           61
5367      13971        626019           67
5368      13998        535812           74

[5369 rows x 3 columns]

In [10]:
account_df = pd.read_csv(r"/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/account.csv", sep=";")

In [11]:

main_df = disp_df.merge(client_df, on="client_id")

In [12]:
main_df

      disp_id  client_id  account_id       type  birth_number  district_id
0           1          1           1      OWNER        706213           18
1           2          2           2      OWNER        450204            1
2           3          3           2  DISPONENT        406009            1
3           4          4           3      OWNER        561201            5
4           5          5           3  DISPONENT        605703            5
...       ...        ...         ...        ...           ...          ...
5364    13647      13955       11349      OWNER        456030            1
5365    13648      13956       11349  DISPONENT        430406            1
5366    13660      13968       11359      OWNER        680413           61
5367    13663      13971       11362      OWNER        626019           67
5368    13690      13998       11382      OWNER        535812           74

[5369 rows x 6 columns]

In [13]:
main_df = main_df.merge(account_df, on="account_id")

In [14]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency,date
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707
...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820

In [15]:
trans_features = trans_df.groupby("account_id").agg(
    total_tx=("trans_id", "count"),
    total_amount=("amount", "sum"),
    avg_amount=("amount", "mean"),
    avg_balance=("balance", "mean")
).reset_index()

In [16]:
main_df = main_df.merge(trans_features, on="account_id")

In [17]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency,date,total_tx,total_amount,avg_amount,avg_balance
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458

In [18]:
main_df = main_df.merge(account_df, on="account_id")

In [19]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency_x,date_x,total_tx,total_amount,avg_amount,avg_balance,district_id,frequency_y,date_y
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368,18,POPLATEK MESICNE,950324
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958,61,POPLATEK MESICNE,941001
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407,67,POPLATEK MESICNE,951014
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458,74,POPLATEK MESICNE,950820

In [20]:
main_df = main_df.merge(trans_features, on="account_id", how="left")

In [21]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency_x,date_x,total_tx_x,total_amount_x,avg_amount_x,avg_balance_x,district_id,frequency_y,date_y,total_tx_y,total_amount_y,avg_amount_y,avg_balance_y
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458

In [22]:
main_df = main_df.merge(loan_df, on="account_id", how="left")

In [23]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency_x,date_x,total_tx_x,...,total_tx_y,total_amount_y,avg_amount_y,avg_balance_y,loan_id,date,amount,duration,payments,status
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324,239,...,239,375174.5,1569.767782,15994.008368,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226,478,...,478,3151479.3,6593.052929,36540.704393,4959.0,940105.0,80952.0,24.0,3373.0,A
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226,478,...,478,3151479.3,6593.052929,36540.704393,4959.0,940105.0,80952.0,24.0,3373.0,A
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707,117,...,117,295021.8,2521.553846,26973.506838,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707,117,...,117,295021.8,2521.553846,26973.506838,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526,304,...,304,3957372.2,13017.671711,48769.447039,7304.0,951029.0,419880.0,60.0,6998.0,C
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526,304,...,304,3957372.2,13017.671711,48769.447039,7304.0,951029.0,419880.0,60.0,6998.0,C
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001,378,...,378,2948081.4,7799.157143,36105.771958,7305.0,960806.0,54024.0,12.0,4502.0,A
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014,344,...,344,1330010.5,3866.309593,30469.940407,7308.0,961227.0,129408.0,24.0,5392.0,A
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820,253,...,253,2623161.9,10368.228854,36379.728458,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
main_df.to_csv("all_data.csv", index=False)

In [25]:
main_df.isna().sum()

disp_id              0
client_id            0
account_id           0
type                 0
birth_number         0
district_id_x        0
district_id_y        0
frequency_x          0
date_x               0
total_tx_x           0
total_amount_x       0
avg_amount_x         0
avg_balance_x        0
district_id          0
frequency_y          0
date_y               0
total_tx_y           0
total_amount_y       0
avg_amount_y         0
avg_balance_y        0
loan_id           4542
date              4542
amount            4542
duration          4542
payments          4542
status            4542
dtype: int64

In [26]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   disp_id         5369 non-null   int64
 1   client_id       5369 non-null   int64
 2   account_id      5369 non-null   int64
 3   type            5369 non-null   object
 4   birth_number    5369 non-null   int64
 5   district_id_x   5369 non-null   int64
 6   district_id_y   5369 non-null   int64
 7   frequency_x     5369 non-null   object
 8   date_x          5369 non-null   int64
 9   total_tx_x      5369 non-null   int64
 10  total_amount_x  5369 non-null   float64
 11  avg_amount_x    5369 non-null   float64
 12  avg_balance_x   5369 non-null   float64
 13  district_id     5369 non-null   int64
 14  frequency_y     5369 non-null   object
 15  date_y          5369 non-null   int64
 16  total_tx_y      5369 non-null   int64
 17  total_amount_y  5369 non-null   float64
 18  avg_amount_y    5369 non-null   float64
 19  avg_balance_y   5369 non-null   float64
 20  loan_id         827 non-null    float64
 21  date            827 non-null    float64
 22  amount          827 non-null    float64
 23  duration        827 non-null    float64
 24  payments        827 non-null    float64
 25  status          827 non-null    object
dtypes: float64(11), int64(11), object(4)
memory usage: 1.1+ MB

In [27]:
main_df.drop(columns=["loan_id", "amount", "duration", "payments", "date","status"], inplace=True)

In [28]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   disp_id         5369 non-null   int64
 1   client_id       5369 non-null   int64
 2   account_id      5369 non-null   int64
 3   type            5369 non-null   object
 4   birth_number    5369 non-null   int64
 5   district_id_x   5369 non-null   int64
 6   district_id_y   5369 non-null   int64
 7   frequency_x     5369 non-null   object
 8   date_x          5369 non-null   int64
 9   total_tx_x      5369 non-null   int64
 10  total_amount_x  5369 non-null   float64
 11  avg_amount_x    5369 non-null   float64
 12  avg_balance_x   5369 non-null   float64
 13  district_id     5369 non-null   int64
 14  frequency_y     5369 non-null   object
 15  date_y          5369 non-null   int64
 16  total_tx_y      5369 non-null   int64
 17  total_amount_y  5369 non-null   float64
 18  avg_amount_y    5369 non-null   float64
 19  avg_balance_y   5369 non-null   float64
dtypes: float64(6), int64(11), object(3)
memory usage: 839.0+ KB

In [29]:
main_df

,disp_id,client_id,account_id,type,birth_number,district_id_x,district_id_y,frequency_x,date_x,total_tx_x,total_amount_x,avg_amount_x,avg_balance_x,district_id,frequency_y,date_y,total_tx_y,total_amount_y,avg_amount_y,avg_balance_y
0,1,1,1,OWNER,706213,18,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368,18,POPLATEK MESICNE,950324,239,375174.5,1569.767782,15994.008368
1,2,2,2,OWNER,450204,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
2,3,3,2,DISPONENT,406009,1,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393,1,POPLATEK MESICNE,930226,478,3151479.3,6593.052929,36540.704393
3,4,4,3,OWNER,561201,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
4,5,5,3,DISPONENT,605703,5,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838,5,POPLATEK MESICNE,970707,117,295021.8,2521.553846,26973.506838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,13647,13955,11349,OWNER,456030,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5365,13648,13956,11349,DISPONENT,430406,1,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039,1,POPLATEK TYDNE,950526,304,3957372.2,13017.671711,48769.447039
5366,13660,13968,11359,OWNER,680413,61,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958,61,POPLATEK MESICNE,941001,378,2948081.4,7799.157143,36105.771958
5367,13663,13971,11362,OWNER,626019,67,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407,67,POPLATEK MESICNE,951014,344,1330010.5,3866.309593,30469.940407
5368,13690,13998,11382,OWNER,535812,74,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458,74,POPLATEK MESICNE,950820,253,2623161.9,10368.228854,36379.728458